// Package runner is the service-agnostic engine: it knows what a scenario is,
// collects assertion failures, runs suites in order and emits the report.
//
// Nothing here mentions the service under test. Do not edit this file per
// service; put service knowledge in harness/ and expectations in scenarios/.
package runner

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"runtime/debug"
	"sort"
	"strings"
	"time"
)

// Status of a finished scenario.
const (
	StatusPass = "PASS"
	StatusFail = "FAIL"
	StatusSkip = "SKIP"
)

// T is handed to every scenario. It collects failures instead of aborting, so
// one scenario reports every way it disagreed with the service rather than
// only the first. It satisfies testify's require/assert TestingT interface,
// so `assert.Equal(t, ...)` works unchanged.
type T struct {
	name     string
	failures []string
	notes    []string
	skipped  string
	verbose  bool
}

// Errorf records a failure. This is the whole interface testify's assert needs.
func (t *T) Errorf(format string, args ...any) {
	t.failures = append(t.failures, strings.TrimRight(fmt.Sprintf(format, args...), "\n"))
}

// Fatalf records a failure and stops the scenario.
func (t *T) Fatalf(format string, args ...any) {
	t.Errorf(format, args...)
	panic(errAbort{})
}

// Fatal stops the scenario when an error makes the rest of it meaningless.
func (t *T) Fatal(err error) { t.Fatalf("%v", err) }

// Check records err as a failure and stops, when err is non-nil.
func (t *T) Check(err error, whileDoing string) {
	if err != nil {
		t.Fatalf("%s: %v", whileDoing, err)
	}
}

// Logf adds a note shown with -v and kept in the JSON output.
func (t *T) Logf(format string, args ...any) {
	note := fmt.Sprintf(format, args...)
	t.notes = append(t.notes, note)
	if t.verbose {
		fmt.Printf("      %s\n", note)
	}
}

// Skipf marks the scenario as not applicable and stops it.
func (t *T) Skipf(format string, args ...any) {
	t.skipped = fmt.Sprintf(format, args...)
	panic(errAbort{})
}

// Failed reports whether anything has been recorded against this scenario.
func (t *T) Failed() bool { return len(t.failures) > 0 }

// Name is the running scenario's name.
func (t *T) Name() string { return t.name }

type errAbort struct{}

// Scenario is one behaviour, named as a sentence about the service.
//
// Doc names the promise it pins and where that promise was made. When the
// scenario fails, Doc is what tells the reader whether the service or the
// suite is wrong, so it is not optional.
type Scenario struct {
	Name string
	Doc  string
	Run  func(t *T)
}

// Suite is an ordered group of scenarios covering one area.
type Suite struct {
	Name string
	What string
	// Setup runs once before the suite; a failure skips the whole suite.
	Setup func() error
	// Teardown always runs, including after a failure.
	Teardown  func()
	Scenarios []Scenario
}

// Result is one finished scenario, in the shape build_report.py consumes.
type Result struct {
	Suite    string   `json:"suite"`
	Name     string   `json:"name"`
	Doc      string   `json:"doc"`
	Status   string   `json:"status"`
	Detail   string   `json:"detail,omitempty"`
	Notes    []string `json:"notes,omitempty"`
	Duration string   `json:"duration"`
}

// Runner executes suites in order and reports.
type Runner struct {
	Filter  *regexp.Regexp
	Verbose bool
	Results []Result
}

// Run executes every scenario whose "suite/name" matches the filter, in
// declaration order, and returns false when any of them failed.
func (r *Runner) Run(suites []Suite) bool {
	ok := true
	for _, s := range suites {
		selected := make([]Scenario, 0, len(s.Scenarios))
		for _, sc := range s.Scenarios {
			if r.Filter == nil || r.Filter.MatchString(s.Name+"/"+sc.Name) {
				selected = append(selected, sc)
			}
		}
		if len(selected) == 0 {
			continue
		}
		fmt.Printf("\n== %s ==\n", s.Name)
		if s.Setup != nil {
			if err := s.Setup(); err != nil {
				fmt.Printf("   setup failed: %v\n", err)
				for _, sc := range selected {
					r.Results = append(r.Results, Result{
						Suite: s.Name, Name: sc.Name, Doc: sc.Doc,
						Status: StatusSkip, Detail: fmt.Sprintf("suite setup failed: %v", err),
					})
				}
				ok = false
				continue
			}
		}
		for _, sc := range selected {
			if !r.one(s.Name, sc) {
				ok = false
			}
		}
		if s.Teardown != nil {
			s.Teardown()
		}
	}
	return ok
}

func (r *Runner) one(suite string, sc Scenario) bool {
	t := &T{name: sc.Name, verbose: r.Verbose}
	started := time.Now()

	func() {
		defer func() {
			if rec := recover(); rec != nil {
				if _, aborted := rec.(errAbort); !aborted {
					t.Errorf("panicked: %v\n%s", rec, debug.Stack())
				}
			}
		}()
		sc.Run(t)
	}()

	res := Result{
		Suite: suite, Name: sc.Name, Doc: sc.Doc,
		Notes: t.notes, Duration: time.Since(started).Round(time.Millisecond).String(),
	}
	switch {
	case t.skipped != "":
		res.Status, res.Detail = StatusSkip, t.skipped
	case len(t.failures) > 0:
		res.Status, res.Detail = StatusFail, strings.Join(t.failures, "\n")
	default:
		res.Status = StatusPass
	}
	r.Results = append(r.Results, res)

	mark := map[string]string{StatusPass: "ok  ", StatusFail: "FAIL", StatusSkip: "skip"}[res.Status]
	fmt.Printf("   %s %-58s %s\n", mark, sc.Name, res.Duration)
	if res.Status == StatusFail {
		for _, line := range strings.Split(res.Detail, "\n") {
			fmt.Printf("        %s\n", line)
		}
	}
	return res.Status != StatusFail
}

// Summary prints the per-suite table that opens the conversation report.
func (r *Runner) Summary() {
	type tally struct{ pass, fail, skip int }
	counts := map[string]*tally{}
	var order []string
	for _, res := range r.Results {
		if _, seen := counts[res.Suite]; !seen {
			counts[res.Suite] = &tally{}
			order = append(order, res.Suite)
		}
		switch res.Status {
		case StatusPass:
			counts[res.Suite].pass++
		case StatusFail:
			counts[res.Suite].fail++
		default:
			counts[res.Suite].skip++
		}
	}
	fmt.Printf("\n%-34s %6s %6s %6s\n", "SUITE", "PASS", "FAIL", "SKIP")
	var tp, tf, ts int
	for _, name := range order {
		c := counts[name]
		fmt.Printf("%-34s %6d %6d %6d\n", name, c.pass, c.fail, c.skip)
		tp, tf, ts = tp+c.pass, tf+c.fail, ts+c.skip
	}
	fmt.Printf("%-34s %6d %6d %6d\n", "total", tp, tf, ts)
}

// WriteJSON writes the results for scripts/build_report.py to consume, so the
// scenario list in the report is never retyped by hand.
func (r *Runner) WriteJSON(path string) error {
	sorted := append([]Result(nil), r.Results...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Suite < sorted[j].Suite })
	body, err := json.MarshalIndent(map[string]any{"scenarios": r.Results}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(body, '\n'), 0o644)
}

// List prints what would run, without running it.
func (r *Runner) List(suites []Suite) {
	for _, s := range suites {
		fmt.Printf("%s\n", s.Name)
		for _, sc := range s.Scenarios {
			if r.Filter == nil || r.Filter.MatchString(s.Name+"/"+sc.Name) {
				fmt.Printf("   %s\n", sc.Name)
			}
		}
	}
}
